### ISSUE TITLE
check-dns.rb --validate doesn't work

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/sensu-plugins-dns#23]
```
root@3e79cf3bf145:/opt/sensu/embedded/bin# ./check-dns.rb -d www.google.com --validate
Check failed to run: undefined local variable or method `error' for #<DNS:0x00000002c3f4b8>
Did you mean?  errors, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-dns-1.2.1/bin/check-dns.rb:204:in `block in check_results'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-dns-1.2.1/bin/check-dns.rb:165:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-dns-1.2.1/bin/check-dns.rb:165:in `check_results'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-dns-1.2.1/bin/check-dns.rb:229:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```
This is in Ubuntu 16.04 docker container with Sensu 0.29.0-11 installed from Sensu APT repo. "dns" plugin was installed with `sensu-install`.

**Comment by majormoses** [comment]
currently not all the plugins support 0.29 as there was a lopt of breaking changes due to using ruby 2.4 which has a ton of breaking changes. Here is the meta issue: https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/26

**Comment by majormoses** [comment]
That being said this looks pretty unrelated, I will take a quick peak and see if there is something obvious.

**Comment by majormoses** [comment]
yup found it, silly issue. I will have a hotfix shortly.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-dns/versions/1.2.2
