### ISSUE TITLE
Cut a new Gem Release

### ISSUE THREAD

**Issue by jgnagy** [sensu-plugins/sensu-plugins-dns#7]
Given the latest PR merges, can you bump the gem version and release a new gem so these changes can be rolled out the right way?

**Comment by nhinds** [comment]
@sstarcher as you merged the PRs, are you able to perform the release? Is this blocked on anything?

**Comment by eheydrick** [comment]
New release coming as soon as travis starts building again

**Comment by eheydrick** [comment]
I just tagged 1.0.0. It'll be on rubygems as soon as travis gets around to building it.
