### ISSUE TITLE
Depreciated 

### ISSUE THREAD

**Issue by breatheasia** [sensu-plugins/sensu-plugins-dns#9]
After upgrading sensu to 0.23, I'm now getting the following error with the DNS plugin.

/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/dnsruby-1.58.0/lib/dnsruby.rb:165: warning: constant Dnsruby::TimeoutError is deprecated

There is a newer version of the DNSRUBY gem (1.59.2) available.

**Comment by nhinds** [comment]
This was fixed in #8 but is not yet released

**Comment by eheydrick** [comment]
Fixed in 1.0.0
